# Server properties
server:
  port: 8140

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Search Service - Local Instance

# Spring application properties
spring:
  application:
    name: discovery-search
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:./env.properties
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}
    username: ${ES_USERNAME:user}
    password: ${ES_PASSWORD:pass}
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

# Eureka configuration
eureka:
  client:
    fetchRegistry: ${EUREKA_DISCOVERY_ENABLED:false}
    registerWithEureka: ${EUREKA_DISCOVERY_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE:dummy-exchange}
  queues:
    add-update-content: ${RMQ_ADD_UPDATE_CONTENT_Q:dummy-queue}
    delete-content: ${RMQ_DELETE_CONTENT_Q:dummy-queue}
  routing-keys:
    add-update-content: ${RMQ_ADD_UPDATE_CONTENT_RK:dummy-key}
    delete-content: ${RMQ_DELETE_CONTENT_RK:dummy-key}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.vsp: DEBUG
