# Server properties
server:
  port: 8096

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: Search Service
    description: Search Service Local Instance

# Spring application properties
spring:
  application:
    name: search
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL}
      - optional:file:./env.properties
  elasticsearch:
    rest:
      uris: ${ES_URIS}
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE}
  queues:
    add-update-content: ${RMQ_ADD_UPDATE_CONTENT_Q}
    delete-content: ${RMQ_DELETE_CONTENT_Q}
  routing-keys:
    add-update-content: ${RMQ_ADD_UPDATE_CONTENT_RK}
    delete-content: ${RMQ_DELETE_CONTENT_RK}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG